#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

readonly SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"

readonly a=sample
readonly b=wormholes_local
readonly inventory_dir="$SCRIPT_DIR/../inventory"
readonly a_inventory=$inventory_dir/$a
readonly b_inventory=$inventory_dir/$b

diff_file() {
  local b_filepath=$1
  if [[ -f "$a_inventory/$b_filepath" ]]; then
    diff -u "$a_inventory/$b_filepath" "$b_inventory/$b_filepath" | diff-so-fancy
  fi
}

main() {
  pushd "$b_inventory"

  local filepath
  while read -rd '' filepath; do
    diff_file "$filepath"
  done < <(find . -type f -name '*.yml' -print0)

  popd
}

main
