#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

readonly SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"

ansible-playbook \
  -e ansible_become_pass=vagrant \
  -i "$SCRIPT_DIR"/../inventory/wormholes_local \
  -l "all,localhost" \
  -b --flush-cache -vvv \
  "$SCRIPT_DIR"/../cluster.yml
