#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

readonly SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"

# shellcheck source=./common_vars.sh
source "$SCRIPT_DIR"/common_vars.sh

VAGRANT_CWD=$SCRIPT_DIR/.. vagrant destroy --force

files=(
  vagrant_ansible_inventory
  artifacts
  credentials
)

for file in "${files[@]}"; do
  path="$SCRIPT_DIR"/../inventory/$INV/$file
  echo "[TODO] rm $path"
  rm -rf "$path"
done

echo '[DONE]'
