---

- set_fact:
    offline_repo_dir: /var/lib/yum_repo/{{ ansible_architecture }}/{{ ansible_distribution_major_version }}/offline

- name: install rpm createrepo
  shell: yum -C install -y {{ offline_repo_dir }}/createrepo/packages/*.rpm
  register: install_createrepo_cmd
  failed_when: "install_createrepo_cmd.rc != 0 and install_createrepo_cmd.stderr != 'Error: Nothing to do'"

- name: create offline repo
  shell: createrepo {{ offline_repo_dir }}

- name: add yum_repository
  yum_repository:
    name: offline
    description: offline repo for kubespray
    baseurl: file://{{ offline_repo_dir }}
    enabled: no
    gpgcheck: no
    # gpgcheck: yes
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

- name: Install packages requirements for CentOS
  yum:
    name: "{{ required_pkgs | default([]) | union(common_required_pkgs|default([])) }}"
    state: latest
    disablerepo: "*"
    enablerepo: offline
  register: pkgs_task_result
  until: pkgs_task_result is succeeded
  retries: 4
  delay: "{{ retry_stagger | random + 3 }}"
